spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_balance
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cache:
    type: redis
    redis:
      host: localhost
      port: 6379

  elasticsearch:
    uris: http://localhost:9200